{{ if .Values.deployMonitor }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: cadvisor
  name: kubestar-cadvisor
  namespace: kubestar-monitor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: cadvisor
  name: kubestar-cadvisor
rules:
  - apiGroups:
      - policy
    resourceNames:
      - cadvisor
    resources:
      - podsecuritypolicies
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: cadvisor
  name: kubestar-cadvisor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cadvisor
subjects:
  - kind: ServiceAccount
    name: kubestar-cadvisor
    namespace: kubestar-monitor
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cadvisor
    name: cadvisor
  name: cadvisor
  namespace: kubestar-monitor
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: cadvisor
    name: cadvisor
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: cadvisor
  name: cadvisor
  namespace: kubestar-monitor
spec:
  selector:
    matchLabels:
      app: cadvisor
      name: cadvisor
  template:
    metadata:
      labels:
        app: cadvisor
        name: cadvisor
    spec:
      automountServiceAccountToken: false
      containers:
        - args:
            - --housekeeping_interval=10s
            - --max_housekeeping_interval=15s
            - --event_storage_event_limit=default=0
            - --event_storage_age_limit=default=0
            - --enable_metrics=tcp
            - --docker_only=true
            - --store_container_labels=false
            - --whitelisted_container_labels=io.kubernetes.container.name,io.kubernetes.pod.name,io.kubernetes.pod.namespace
          {{if .Values.ContainerRuntimeContainerd }}
          image: gcr.io/cadvisor/cadvisor:v0.45.0-containerd-cri
          {{end}}
          {{if .Values.ContainerRuntimeDocker }}
          image: gcr.io/cadvisor/cadvisor:v0.45.0
          {{end}}
          name: cadvisor
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - mountPath: /rootfs
              name: rootfs
              readOnly: true
            - mountPath: /var/run
              name: var-run
              readOnly: true
            - mountPath: /run
              name: run
            - mountPath: /sys
              name: sys
              readOnly: true
            {{if .Values.ContainerRuntimeDocker }}
            - mountPath: /var/lib/docker
              name: docker
              readOnly: true
            {{end}}
            {{if .Values.ContainerRuntimeContainerd }}
            - mountPath: /var/lib/containerd
              name: containerd
              readOnly: true
            {{end}}
      serviceAccountName: kubestar-cadvisor
      serviceAccount: kubestar-cadvisor
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /
          name: rootfs
        - hostPath:
            path: /var/run
          name: var-run
        - hostPath:
            path: /run
          name: run
        - hostPath:
            path: /sys
          name: sys
        {{if .Values.ContainerRuntimeDocker }}
        - hostPath:
            path: /var/lib/docker
          name: docker
        {{end}}
        {{if .Values.ContainerRuntimeContainerd }}
        - hostPath:
            path: /var/lib/containerd
          name: containerd
        {{end}}
{{end}}
