{{ if .Values.deployKubeStar }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubestar-mysql
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: kubestar-mysql
      type: Deployment
  replicas: 1
  template:
    metadata:
      name: kubestar-mysql
      labels:
        type: Deployment
        app: kubestar-mysql
    spec:
      containers:
        - name: kubestar-mysql
          image: mysql:5.7
          ports:
            - name: mysql-port
              containerPort: 3306
              protocol: "TCP"
          resources:
            limits:
              cpu: 1
              memory: 1G
            requests:
              cpu: 500m
              memory: 500M
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
            - name: MYSQL_DATABASE
              value: "kubestar"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: kubestar-mysql-storage-data
      {{if .Values.StorageClassName }}
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        fsGroup: 1000
      {{end}}
      {{if not (.Values.StorageClassName) }}
      nodeName: {{ .Release.SelectedNodeName }}
      {{end}}
      volumes:
        - name: kubestar-mysql-storage-data
          {{if .Values.StorageClassName }}
          persistentVolumeClaim:
            claimName: "kubestar-mysql-pvc"
          {{end}}
          {{if not (.Values.StorageClassName) }}
          hostPath:
            path: /data/kubestar/mysql
            type: DirectoryOrCreate
          {{end}}

{{if .Values.StorageClassName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kubestar-mysql
    type: Deployment
  name: kubestar-mysql-pvc
  namespace: kubestar
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: {{ .Values.StorageClassName }}
{{end}}
---

apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: kubestar-mysql
    type: Deployment
  name: kubestar-mysql
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: port1
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: kubestar-mysql
    type: Deployment
  type: ClusterIP
{{end}}